### PR TITLE
The little details - Commands' category and description

### PR DESCRIPTION
**Pull request by pedrorgirardi**
Hi @PEZ,

Not sure if it's okay to change a command's category to Calva - might confuse users? - but I did it to all of them. Also did some minor changes to commands description.

I just tried Calva with Shadow CLJS and it was easy to get it working, I'm very happy to see this! I've been teaching ClojureScript to new programmers and the editor integration has been a little bit of an issue. I use Cursive, but IDEs scare them off (I don't really understand it, it seems to be something psychological, not technical), and Emacs is even scarier and I'm not good at it to teach either. VSCode in the other hand is very popular and it's a very nice editor, so when they see that they can use VSCode for ClojureScript it's a thing less to learn (worry) and they feel more comfortable. 

I'm sure that the work you have done with Calva will make a newcomer's experience better and easier to get started. I hope more people give this extension a go! 😃

### CODE REVIEW

**Comment by PEZ** [comment]
Many thanks for this help! Yes, this is totally the right thing to do.

I should change the settings category as well, but worry that it will mess up settings for existing users. But I probably should do it before the user base grows and a change will mess up for even more people.

Very happy to hear the extension works for you. Thomas Heller (the creator of `shadow-cljs`) provided me some feedback about how it might be a bit lacking for real world shadow projects with several builds. I am pondering how to support that better, but for educational purposes maybe there is most often just one or a few builds and not so much switching between them.

Please let me know how your students find it. I really would like it to be a good fit for beginners, even though I hope I will be able to support experienced users with real world projects as well. (I doubt I can ever match Cursive, of course.)

Cheers, and thanks again!

**Comment by PEZ** [comment]
And now I have published your patch to the marketplace. Please upgrade. 😄

**Comment by pedrorgirardi** [comment]
Thank YOU @PEZ ! 

This morning a friend of mine was having an issue with ProtoREPL, I don't use ProtoREPL so I don't really know much about it, so I showed him VSCode and Calva. He downloaded VSCode and installed Calva straight away. I was a little bit afraid of the initial setup, but it actually worked without any configuration at all. 👍👍👍

Thomas Heller is a very nice guy and very keen to help. He probably has some really good considerations. :)

I will use more Calva and try to take note of things that don't seem right.

Cheers!

**Comment by PEZ** [comment]
Great! Let your friend now that if he has feedback on Calva, I am all ears. The `editors` channel in the Clojurians Slack is a good way to reach me. https://clojurians.slack.com/messages/editors/ Or, just file an issue. Or, even better than issues, PRs, following your lead. 😄

**Comment by pedrorgirardi** [comment]
Cool!! I didn't know about the editorss room in Clojurians.

**Comment by pedrorgirardi** [comment]
Nice!! Thank you!

Just one question. Why does `clojure.format.enable` is not `calva.format.enable`?

**Pull request merged**
